### ISSUE TITLE
App throws an exception (without crashing) when delete confirmation dialog is shown and screen rotates

### ISSUE THREAD

**Issue by eucalypto** [eucalypto/time-tracker#22]
When the delete confirmation dialog is shown (for both category and activity) and the screen rotates, the app does not crash, but the dialog disappears.

From Logcat you can see an exception was thrown:

```
2021-07-25 11:11:59.286 6575-6575/net.eucalypto.timetracker E/WindowManager:
android.view.WindowLeaked: Activity net.eucalypto.timetracker.MainActivity has leaked window
DecorView@41d6b81[MainActivity] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:598)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:377)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:96)
        at android.app.Dialog.show(Dialog.java:342)
        at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1009)
        at net.eucalypto.timetracker.activities.ActivityListFragment.showDeleteConfirmationDialog(ActivityListFragment.kt:123)
        at net.eucalypto.timetracker.activities.ActivityListFragment.access$showDeleteConfirmationDialog(ActivityListFragment.kt:24)
        at net.eucalypto.timetracker.activities.ActivityListFragment$setupRecyclerView$1.invoke(ActivityListFragment.kt:54)
        at net.eucalypto.timetracker.activities.ActivityListFragment$setupRecyclerView$1.invoke(ActivityListFragment.kt:54)
        at net.eucalypto.timetracker.activities.ActivityViewHolder.showContextMenu$lambda-3$lambda-2(ActivityAdapter.kt:91)
        at net.eucalypto.timetracker.activities.ActivityViewHolder.lambda$RBtl_1Fp8hppOLK_6lN5o82GZmY(Unknown Source:0)
        at net.eucalypto.timetracker.activities.-$$Lambda$ActivityViewHolder$RBtl_1Fp8hppOLK_6lN5o82GZmY.onMenuItemClick(Unknown Source:8)
        at androidx.appcompat.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:113)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
        at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
        at android.widget.AdapterView.performItemClick(AdapterView.java:330)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1213)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3221)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

**Comment by eucalypto** [comment]
Well, I haven't used DialogFragment for dialog. Instead, I used AlertDialog directly (using it's .show() method).

It looked fine enough. On screen rotation, the dialog disappeared, but that was not that bad. But now knowing that it might be a leak, it has to change.

=> So why not use DialogFragment and let the fragment manager deal with stuff like that?

This DeleteConfirmationDialogFragment needs to receive an activity data object to delete and needs access to the viewModel to actually activate the deletion.

See:
- https://stackoverflow.com/questions/63674143/how-to-send-data-from-dialogfragment-to-fragment-using-viewmodel
- https://developer.android.com/topic/libraries/architecture/viewmodel#sharing
